### ISSUE TITLE
Dont press gimmick notes

### ISSUE THREAD

**Issue by Skeleton19** [Mati278/FNB-Autoplayer#13]
I guess if im using synapse x and this gimmick notes is "onhit" as shows dark dex, autoplayer should press it but no.

https://user-images.githubusercontent.com/50092873/212954102-7cf2181a-ad61-4d35-9b56-b2c962a4dbf1.mov

**Comment by Mati278** [comment]
man i feel sleepy

**Comment by Skeleton19** [comment]
> man i feel sleepy

Man, now autoplayer dont see usual notes.
