### ISSUE TITLE
Script isn't executing (Krnl)

### ISSUE THREAD

**Issue by Kirll-cpu** [Mati278/FNB-Autoplayer#3]
Script isn't executing for some reason, it stopped executing it just today.
![Roblox VR Screenshot 2022 07 29 - 17 43 46 48](https://user-images.githubusercontent.com/65349540/181787310-30d3e963-8594-4ea2-814f-bc5b05207747.png)

**Comment by Kirll-cpu** [comment]
i probably won't get any notifications if somebody's going to comment here.

**Comment by Mati278** [comment]
blame stavratum

**Comment by Kirll-cpu** [comment]
> blame stavratum

ok
