### ISSUE TITLE
Script isn't working.

### ISSUE THREAD

**Issue by Kirll-cpu** [Mati278/FNB-Autoplayer#4]
hey, you probably remember me, it's me again, and it's not executing the script again, i tried like 4 times and then decided to execute stavratum's version, which is worked, and i probably will not answer if you or somebody else will comment this, but can you fix this issue?
![Roblox VR Screenshot 2022 10 01 - 15 50 53 03](https://user-images.githubusercontent.com/65349540/193410516-573542f4-2da5-4525-aedb-453fc5f4b228.png)

**Comment by Kirll-cpu** [comment]
uhh, hello?

**Comment by Kirll-cpu** [comment]
yo man, 3 days already, is everything ok?

**Comment by Kirll-cpu** [comment]
bro, you vanished?

**Comment by Mati278** [comment]
i went to piss on the moon, srry

**Comment by Kirll-cpu** [comment]
> i went to piss on the moon, srry

ok, lol.
