### ISSUE TITLE
Dont hit arrows (notes)

### ISSUE THREAD

**Issue by Skeleton19** [Mati278/FNB-Autoplayer#5]
Even when Im try to use virtual input or fire signal, it dont see arrows (notes). I tried to use one method associated with the offsets list. I have scroll speed 2, so I set 17 for hit offset, but it also didn't work.

**Comment by Mati278** [comment]
1. is fixed now (maybe)
2. offset no longer depends on scroll speed
3. that offset list on the repo is for point n°1
